### ISSUE TITLE
The problem of model training time

### ISSUE THREAD

**Issue by bumbumya** [nikitacs16/xlift_dst#1]
Hey, guys! your paper said training  a SUMBT model takes approx six hours on RTX 2080 Ti, but I need over 40 hours on A40. I set batch_size=16 and used mbert_uncased, other settings remain unchanged. Did I get something wrong?

**Comment by bumbumya** [comment]
> Hey, guys! your paper said training a SUMBT model takes approx six hours on RTX 2080 Ti, but I need over 40 hours on A40. I set batch_size=16 and used mbert_uncased, other settings remain unchanged. Did I get something wrong?

**Comment by nikitacs16** [comment]
Hello
Sorry for the delay - I was away. 
This is strange. I think your setting looks okay to me. 

We have used Transformers v4.2.2 for all the experiments. I hope that version is consistent. 

Can I check if after 40 hours, you were able to reproduce the results mentioned in the paper? 
If not, please also check the original  [repository](https://github.com/thu-coai/ConvLab-2). My code only modifies the part of their code to use config files. 

Please reach out to me at nikita.moghe@ed.ac.uk if further questions.
